version: '1.2'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: casasolam
      POSTGRES_PASSWORD: Marisol123
      POSTGRES_DB: Prueba

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
